apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ughi.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ughi.name" . }}
    helm.sh/chart: {{ include "ughi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ughi.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ughi.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: UGHI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ughi.fullname" . }}-secret
                  key: ughi-master-key
            - name: UGHI_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ughi.fullname" . }}-secret
                  key: ughi-jwt-secret
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: ughi-data
              mountPath: /home/UGHI/data
      volumes:
        - name: ughi-data
          emptyDir: {}
